package com.oraculum.company.api.dto;

import com.oraculum.company.domain.SharePriceSignalEntity;

import java.time.LocalDate;

public record SharePriceSignalDto(
        LocalDate tradeDate,
        int companyId,
        String ticker,
        String market,
        String flagLastDayOfMonth,
        String currency,
        Float sharePrice,
        Integer volume,
        Float pctFrom50dMa,
        Float pctFrom200dMa,
        Float volumeVelocity,
        Integer activeFiscalYear,
        String activeFiscalPeriod,
        LocalDate activeReportPublishDate,
        Float marketCapitalization,
        Float peRatio,
        Float earningsYield,
        Float priceToFcf,
        Float priceToSales,
        Float priceToBook,
        Float priceToNcav,
        Float priceToNnwc,
        int isGrahamNetNet,
        Float enterpriseValue,
        Float enterpriseValueToEbitda,
        Float returnOnCapitalEmployed,
        Float returnOnEquity,
        Float netMargin,
        Float currentRatio,
        Float debtToEquity,
        Float fcfYield,
        Float enterpriseValueToRevenue,
        Float enterpriseValueToFreeCashFlow,
        Float returnOnAssets,
        Float grossMargin,
        Float operatingMargin,
        Float fcfMargin,
        Float quickRatio,
        Float interestCoverageRatio,
        Float grahamMarginOfSafety,
        Integer isGrahamDefensive,
        Float revenueYoyGrowth,
        Float epsYoyGrowth,
        Integer piotroskiFScore,
        Integer revenueGrowthStreak,
        Integer positiveFcfStreak,
        Integer positiveEarningsStreak,
        Integer isCashEarnings,
        Integer isNegativeEquity,
        Float qualityScore,
        String compositeSignal
) {
    public static SharePriceSignalDto fromEntity(SharePriceSignalEntity entity) {
        if (entity == null)
            return null;
        return new SharePriceSignalDto(
                entity.getTradeDate(),
                entity.getCompanyId(),
                entity.getTicker(),
                entity.getMarket(),
                entity.getFlagLastDayOfMonth(),
                entity.getCurrency(),
                entity.getSharePrice(),
                entity.getVolume(),
                entity.getPctFrom50dMa(),
                entity.getPctFrom200dMa(),
                entity.getVolumeVelocity(),
                entity.getActiveFiscalYear(),
                entity.getActiveFiscalPeriod(),
                entity.getActiveReportPublishDate(),
                entity.getMarketCapitalization(),
                entity.getPeRatio(),
                entity.getEarningsYield(),
                entity.getPriceToFcf(),
                entity.getPriceToSales(),
                entity.getPriceToBook(),
                entity.getPriceToNcav(),
                entity.getPriceToNnwc(),
                entity.getIsGrahamNetNet(),
                entity.getEnterpriseValue(),
                entity.getEnterpriseValueToEbitda(),
                entity.getReturnOnCapitalEmployed(),
                entity.getReturnOnEquity(),
                entity.getNetMargin(),
                entity.getCurrentRatio(),
                entity.getDebtToEquity(),
                entity.getFcfYield(),
                entity.getEnterpriseValueToRevenue(),
                entity.getEnterpriseValueToFreeCashFlow(),
                entity.getReturnOnAssets(),
                entity.getGrossMargin(),
                entity.getOperatingMargin(),
                entity.getFcfMargin(),
                entity.getQuickRatio(),
                entity.getInterestCoverageRatio(),
                entity.getGrahamMarginOfSafety(),
                entity.getIsGrahamDefensive(),
                entity.getRevenueYoyGrowth(),
                entity.getEpsYoyGrowth(),
                entity.getPiotroskiFScore(),
                entity.getRevenueGrowthStreak(),
                entity.getPositiveFcfStreak(),
                entity.getPositiveEarningsStreak(),
                entity.getIsCashEarnings(),
                entity.getIsNegativeEquity(),
                entity.getQualityScore(),
                entity.getCompositeSignal()
        );
    }
}