-- Flyway migration script for creating partitioned LLM execution log table
CREATE TABLE public.t_llm_execution_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    correlation_id UUID,
    correlation_type VARCHAR(50),
    source VARCHAR(50),
    provider_code VARCHAR(50),
    model_name VARCHAR(100),
    input_tokens INTEGER,
    output_tokens INTEGER,
    total_tokens INTEGER,
    prompt TEXT,
    response JSONB,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);


