CREATE TABLE t_api_usage (
    provider VARCHAR(255) PRIMARY KEY,
    last_usage_date DATE NOT NULL,
    call_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
